from collections import deque
from typing import Protocol, runtime_checkable


@runtime_checkable
class ModeHandler(Protocol):
    def on_startup(self) -> None: ...
    def startup_description(self) -> str: ...
    def on_transcription(self, text: str, word_buffer: deque) -> None: ...
